server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: ssh://git@github.com:tbharti/spring-cloud-config.git
  security:
    user:
      name: admin
      password: admin